// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/image-proxy': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image-proxy').default>>>>
    }
    '/api/list-images': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/list-images').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login').default>>>>
    }
    '/api/order': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/order').default>>>>
    }
    '/api/presign': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/presign').default>>>>
    }
    '/api/print-options': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/print-options').default>>>>
    }
    '/api/products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products').default>>>>
    }
    '/api/send-email': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/send-email').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}