// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/13 18:30:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/nashi/malias-7-8/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/plugins/**/*.{js,ts,mjs}","C:/Users/nashi/malias-7-8/composables/**/*.{js,ts,mjs}","C:/Users/nashi/malias-7-8/utils/**/*.{js,ts,mjs}","C:/Users/nashi/malias-7-8/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/nashi/malias-7-8/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;